### ISSUE TITLE
Codegen doesn't generate public constructor for SwiftBaseListener

### ISSUE THREAD

**Issue by artyom-razinov** [janyou/ANTLR-Swift-Target#1]
Steps to reproduce:
1. Generate some grammar.

Actual result:

```
public class SwiftBaseListener: SwiftListener {
    /**
     * {@inheritDoc}
     *
     * <p>The default implementation does nothing.</p>
     */
    public func enterTop_level(ctx: SwiftParser.Top_levelContext) { }
```

Expected result:

```
public class SwiftBaseListener: SwiftListener {
    public init() {
    }

    /**
     * {@inheritDoc}
     *
     * <p>The default implementation does nothing.</p>
     */
    public func enterTop_level(ctx: SwiftParser.Top_levelContext) { }
```

Notes:
Constructor should be public for use in frameworks.

**Comment by janyou** [comment]
I am not sure what you mean.

```
  public init() {
    }
```

it‘s necessary?

sample(no error):

```
public class MyListener: SwiftBaseListener {
    public var something: String
    public init(something: String){
        self.something = something
    }
    public override func enterTopLevel(ctx: SwiftParser.TopLevelContext) { }
}
```

**Comment by artyom-razinov** [comment]
It is necessary. Assume you have a framework with SwiftBaseListener. And you link it into your project. Your project has MyListener. And it won't compile, because SwiftBaseListener has no public init.

**Comment by artyom-razinov** [comment]
The issue only reproduces when SwiftBaseListener is in linked framework.

**Comment by janyou** [comment]
I tried, there was no compile error.

**Comment by artyom-razinov** [comment]
[SwiftGrammar.zip](https://github.com/janyou/ANTLR-Swift-Target/files/213373/SwiftGrammar.zip)

Open this project, run tests (⌘ U)

**Comment by janyou** [comment]
I didn't expect you to use SwiftBaseListener like this.
If SwiftWalker is in SwiftGrammar project, there was no compile error.
I will add it.
