### ISSUE TITLE
feature - support for alternative outputs

### ISSUE THREAD

**Issue by johndpope** [janyou/ANTLR-Swift-Target#2]
I'm working on a python to swift converter using the code from objc2swift yahoo project.
https://github.com/yahoojapan/objc2swift

I can't get it to work without the scala files to match the tokens from the python3.g4 grammar.
https://github.com/antlr/grammars-v4/blob/master/python3/Python3.g4

I did open up a ticket - but no answers yet. 
https://github.com/yahoojapan/objc2swift/issues/22

I found this java code for targeting scala. I think it's a bit out of date.
It would be awesome if this project supported other targets and I could just throw this in. 
https://github.com/bdkent/antlr4-scala-target-example/issues/1

Appreciate any help on this. Thanks

Potential list of targets
https://github.com/antlr/grammars-v4

**Comment by janyou** [comment]
You can use ANTLR-Java-Target to generate java code and then call java with Scala.
