### ISSUE TITLE
Generated visitor missing superclass methods

### ISSUE THREAD

**Issue by slcott** [janyou/ANTLR-Swift-Target#3]
I had to make a small fix in order to get tne  the calculator example project (based on the Expr.g4 grammar) to work correctly.

I changed

```
public class ExprVisitor<T>: ParseTreeVisitor<T> {
```

to

```
public class ExprVisitor<T>: AbstractParseTreeVisitor<T> {
```

It's probably not good to make the change for long term and is inconsistent with the antlr4 java runtime, but works for now.
Here is the full code file for this class to paint a fuller picture:

**Comment by janyou** [comment]
Should you use the **ExprBaseVisitor** class?

**Comment by slcott** [comment]
That fix is a good temporary solution, but causes other problems.

Running `antlr4 -visitor Expr.g4` produces a visitor (in java) with this signature
```
public interface ExprVisitor<T> extends ParseTreeVisitor<T> {
```

This is inconsistent with running `java -cp antlr4-4.5.1.jar  org.antlr.v4.Tool -Dlanguage=Swift -visitor ../Calc_swift/Calc2/Calc2/Expr.g4` 
which emits
```
public class ExprVisitor<T>: ParseTreeVisitor<T> {
```

I made the change you suggest to 
```
public class ExprVisitor<T>: ExprBaseVisitor<T> {
```

but that causes the following error for all methods in class: `Overriding declaration requires an 'override keyword`

So I have to change each method from 
```
public func visitProg(ctx: ExprParser.ProgContext) -> T{
```
to 
```
override public func visitProg(ctx: ExprParser.ProgContext) -> T{
```

I attached the relevant files.


[Archive.zip](https://github.com/janyou/ANTLR-Swift-Target/files/244158/Archive.zip)

**Comment by janyou** [comment]
ExprVisitor<T>  and ExprBaseVisitor<T> function is not the same.
ExprBaseVisitor<T>  default call **visitChildren**.

```
public  class ExprContext: ParserRuleContext {
             .......
        override
        public func accept<T>(visitor: ParseTreeVisitor<T>) -> T? {
            if visitor is ExprVisitor {
                 return (visitor as! ExprVisitor<T>).visitExpr(self)
            }
            else {
                 return visitor.visitChildren(self)
            }
        }
    }
```

**Comment by slcott** [comment]
First, thank you very much for making this tool, but  
there is a major bug. Look at this output:

**Swift** output
```
// ExprVisitor.swift
public class ExprVisitor<T>: ParseTreeVisitor<T> {

	public func visitProg(ctx: ExprParser.ProgContext) -> T {
		fatalError(#function + " must be overridden")
	}
```
**Java** output
```
// ExprVisior.java
public interface ExprVisitor<T> extends ParseTreeVisitor<T> {
	T visitProg(ExprParser.ProgContext ctx);
```

`ExprVisitor` should not be a **class**. It should be a **protocol!**

It looks like you changed several interfaces to classes. 
You should have used **Associated Types**, i.e. `typealias T` instead. 
It looks like you changed your mind.
```
public class ParseTreeVisitor<T> {
    public init() {

    }
    // typealias T
    /**
     ...
     */
    public func visit(tree: ParseTree) -> T? {
        RuntimeException(" must overriden !")
        return nil

    }
```
Is not equivalent to this:
```
public interface ParseTreeVisitor<T> {
	/**
	 ...
	 */
	T visit(ParseTree tree);
```

Since there's no multiple inheritance the following is a bug. This is java output from the main branch's tool. 
```
public class ExprBaseVisitor<T> extends AbstractParseTreeVisitor<T> implements ExprVisitor<T> {
```
This is equivalent output for the swift target:
```
public class ExprBaseVisitor<T>: AbstractParseTreeVisitor<T> {
```
